kevin-lee/just-fp

project/Deps.scala, src/main/scala/kevinlee/fp/Equal.scala, src/main/scala/kevinlee/fp/JustSyntax.scala, src/main/scala/kevinlee/fp/instances/BigDecimalInstances.scala, src/main/scala/kevinlee/fp/instances/BigIntInstances.scala, src/main/scala/kevinlee/fp/instances/BooleanInstances.scala, src/main/scala/kevinlee/fp/instances/CharInstances.scala, src/main/scala/kevinlee/fp/instances/DoubleInstances.scala, src/main/scala/kevinlee/fp/instances/FloatInstances.scala, src/main/scala/kevinlee/fp/instances/IntInstances.scala, src/main/scala/kevinlee/fp/instances/LongInstances.scala, src/main/scala/kevinlee/fp/instances/ShortInstances.scala, src/main/scala/kevinlee/fp/instances/StringInstances.scala, src/main/scala/kevinlee/fp/syntax/EitherSyntax.scala, src/main/scala/kevinlee/fp/syntax/EqualSyntax.scala, src/test/scala/kevinlee/fp/Gens.scala, src/test/scala/kevinlee/fp/syntax/EqualSyntaxSpec.scala, src/test/scala/kevinlee/fp/testing/TestPredef.scala
* Close #38 - Add Syntax with `===` and `!==`
* `Equal` instances for `Boolean`, `Int`, `Short`, `Long`, `Char`, `Float`, `Double`, `String`, `BigInt` and `BigDecimal` have been added.
=> Close #38 - Add Syntax with === and !==

src/main/scala/kevinlee/fp/syntax/EqualSyntax.scala
Close #46 - EqualOps may cause wrongly converted type
=> Close #46 - EqualOps may cause wrongly converted type

project/ProjectInfo.scala, project/build.properties
Updated: build.sbt and build.properties
- Scala `2.13.0` => `2.13.1`
- sbt `1.2.8` => `1.3.1`
=> Updated: build.sbt and build.properties

src/main/scala/just/fp/syntax/SemiGroupSyntax.scala, src/test/scala/just/fp/syntax/SemiGroupSyntaxSpec.scala
Close #80 - Add `mappend` syntax for `SemiGroup` and `Monoid`
=> Close #80 - Add mappend syntax for SemiGroup and Monoid

src/main/scala/just/fp/EitherT.scala, src/main/scala/just/fp/WriterT.scala
Fixed: names in `EitherT` and `WriterT`
=> Fixed: names in EitherT and WriterT

src/main/scala/just/fp/Monoid.scala, src/main/scala/just/fp/SemiGroup.scala, src/test/scala/just/fp/MonoidSpec.scala, src/test/scala/just/fp/syntax/SemiGroupSyntaxSpec.scala
Close #82 - Add `OptionSemiGroup` and `OptionMonoid`
=> Close #82 - Add OptionSemiGroup and OptionMonoid

src/main/scala/just/fp/package.scala, src/test/scala/just/fp/WriterTSpec.scala
Close #87 - Add `Writer` constructor for `(W, A)`
=> Close #87 - Add Writer constructor for (W, A)

build.sbt, project/ProjectInfo.scala
* Upgraded: 
* `kind-projector` 0.10.3 => 0.11.0
* Scala 2.13.0 => 2.13.1 (since kind-projector now supports full Scala version)
=> Upgraded: kind-projector and Scala

.build-scripts/build-project-simple.sh, .build-scripts/build-project.sh, README.md, build.sbt, changelogs/1.3.0.md, project/ProjectInfo.scala, project/plugins.sbt, src/main/scala/just/fp/EitherT.scala, src/main/scala/just/fp/Monoid.scala, src/main/scala/just/fp/SemiGroup.scala, src/main/scala/just/fp/WriterT.scala, src/main/scala/just/fp/package.scala, src/main/scala/just/fp/syntax/SemiGroupSyntax.scala, src/main/scala/just/fp/syntax/WriterSyntax.scala, src/main/scala/just/fp/syntax/package.scala, src/test/scala/just/fp/MonoidSpec.scala, src/test/scala/just/fp/WriterTSpec.scala, src/test/scala/just/fp/syntax/SemiGroupSyntaxSpec.scala, src/test/scala/just/fp/syntax/WriterSyntaxSpec.scala
* Add writer syntax (#89)
* Add `Writer` constructor for `(W, A)` (#87)
* Add `mappend` syntax for `SemiGroup` and `Monoid` (#80)
* Add `OptionSemiGroup` and `OptionMonoid` (#82)
=> just-fp v1.3.0

README.md, src/main/scala/just/fp/Applicative.scala, src/main/scala/just/fp/EitherT.scala, src/main/scala/just/fp/Equal.scala, src/main/scala/just/fp/Functor.scala, src/main/scala/just/fp/Monad.scala, src/main/scala/just/fp/Monoid.scala, src/main/scala/just/fp/SemiGroup.scala, src/main/scala/just/fp/syntax/SemiGroupSyntax.scala
Close #102 - Added: apply method to the companion objects of most typeclasses to get typeclass instances conveniently
(e.g. `Monoid[List[Int]]` instead of `implicitly[Monoid[List[Int]]]`)
=> Close #102 - Added: apply method to the companion objects of most typeclasses

README.md, changelogs/1.3.2.md, project/ProjectInfo.scala
* Set up GitHub Actions (#113)
* Change group id for publishing to `io.kevinlee` (#116)
**NOTE: No important changes to public. Only the group ID is not `io.kevinlee` which was `kevinlee` before.**
=> just-fp v1.3.2

.github/workflows/release.yml
Close #127 - Use GitHub Actions for Maven Central sync
=> Close #127 - Use GitHub Actions for Maven Central sync

.github/workflows/publish-github-pages.yml
Task #142 - Add document site using sbt-microsites
* publish to GitHub Pages when pushing to publish-docs
=> Task #142 - Add document site using sbt-microsites

build.sbt
* Scala 2.12.10 => 2.12.11
* Since Ammonite does currently not support Scala 2.12.11, it is disabled for Scala 2.12.
=> Upgraded - Scala

build.sbt
Updated: `build.sbt` with `noPublish` setup and `crossScalaVersions` for only the core project
=> Updated: build.sbt

build.sbt
Fixed: `root.dependsOn()` => `root.aggregate()` in `build.sbt`
=> Fixed: root.dependsOn() => root.aggregate()

changelogs/1.4.0.md, project/ProjectInfo.scala
* Add `OptionT` (#132)
* ~~Add the document site using `sbt-microsites`~~ (#142)
* Add core sub-project (#143)
* Replace `sbt-microsites` with `Docusaurus` (#165)
* Build for Dotty (#170)
* ~~Support Scala `3.0.0-M2`~~ (#180)
* Support ~~Scala `3.0.0-M3`~~, Scala `3.0.0-RC1` and Scala `3.0.0-RC2` (#186)
* Use `Scalafix` (#190)
* Drop Scala `3.0.0-M*` support (#192)
=> just-fp v1.4.0

.github/workflows/build.yml, changelogs/1.6.0.md
* Drop Scala `2.10` support (#210)
* Support Scala `3.0.0` (#212)
=> just-fp v1.6.0

project/plugins.sbt
Upgrade: sbt plugins - sbt-mdoc, sbt-docusaur and sbt-devoops
* sbt-mdoc: 2.2.21 => 2.3.2
* sbt-docusaur: 0.5.0 => 0.11.0
* sbt-devoops: 2.6.0 => 2.22.0
=> Upgrade: sbt plugins - sbt-mdoc, sbt-docusaur and sbt-devoops

.github/workflows/build.yml, .github/workflows/m-doc-site-publish.yml, .github/workflows/sbt-build-all.sh, build.sbt, project/build.properties, project/plugins.sbt
Bump sbt and sbt plugins
- sbt to 1.9.4
- sbt-ci-release to 1.5.12
- sbt-scalafix to 0.11.0
- sbt-scalafmt to 2.5.0
- sbt-scoverage to 2.0.8
- sbt-docusaur to 0.13.0
- sbt-devoops to 2.24.0
=> Bump sbt and sbt plugins

.github/workflows/build.yml, .github/workflows/m-doc-site-publish.yml, .github/workflows/release.yml
Update GitHub Actions to use `actions/cache@v4` for SBT and npm caching
=> Update GitHub Actions to use `actions/cache@v4` for SBT and npm caching
