kevin-lee/just-fp

src/main/scala/kevinlee/fp/Applicative.scala, src/main/scala/kevinlee/fp/Functor.scala, src/main/scala/kevinlee/fp/Monad.scala
Closes #2 - Add functor, applicative and monad laws
=> Added: functor, applicative and monad laws

build.sbt
=> just-fp v0.1.0 (2)

build.sbt, project/ProjectInfo.scala
=> just-fp v0.1.0 (3)

build.sbt
* Added: DevOopsGitReleasePlugin
=> just-fp v0.1.0 (4)

build.sbt, project/Deps.scala, src/main/scala/kevinlee/fp/EitherOps.scala, src/main/scala/kevinlee/fp/EitherT.scala, src/main/scala/kevinlee/fp/Implicits.scala, src/test/scala/kevinlee/fp/EitherOpsSpec.scala
Closed #15 - Add right-biased Either
=> Closed #15 - Add right-biased Either

ISSUE_TEMPLATE.md, PULL_REQUEST_TEMPLATE.md, README.md, build.sbt, changelogs/0.2.0.md, project/Deps.scala, project/ProjectInfo.scala, src/main/scala/kevinlee/fp/EitherOps.scala, src/main/scala/kevinlee/fp/EitherT.scala, src/main/scala/kevinlee/fp/Implicits.scala, src/test/scala/kevinlee/fp/EitherOpsSpec.scala
* Add right-biased Either (#15)
=> just-fp v0.2.0

ISSUE_TEMPLATE.md, PULL_REQUEST_TEMPLATE.md, README.md, build.sbt, changelogs/0.2.0.md, project/Deps.scala, project/ProjectInfo.scala, src/main/scala/kevinlee/fp/EitherOps.scala, src/main/scala/kevinlee/fp/EitherT.scala, src/main/scala/kevinlee/fp/Implicits.scala, src/test/scala/kevinlee/fp/EitherOpsSpec.scala
Details: [v0.2.0](https://github.com/Kevin-Lee/just-fp/releases/tag/v0.2.0)
=> Release v0.2.0 => master

src/main/scala/kevinlee/fp/Applicative.scala, src/main/scala/kevinlee/fp/Equal.scala, src/main/scala/kevinlee/fp/Functor.scala, src/main/scala/kevinlee/fp/Monad.scala, src/test/scala/kevinlee/fp/Gens.scala, src/test/scala/kevinlee/fp/MonadSpec.scala, src/test/scala/kevinlee/fp/Specs.scala
Closed #21 - Add type class instance for List
=> Closed #21 - Add type class instance for List

src/main/scala/kevinlee/fp/Equal.scala, src/main/scala/kevinlee/fp/Monad.scala, src/test/scala/kevinlee/fp/Gens.scala, src/test/scala/kevinlee/fp/MonadSpec.scala
Closed #24 - Add Monad type class instance for Vector
=> Closed #24 - Add Monad type class instance for Vector

src/main/scala/kevinlee/fp/Monad.scala, src/test/scala/kevinlee/fp/Gens.scala, src/test/scala/kevinlee/fp/MonadSpec.scala
Closed #20 - Add Monad type class instance for Future
=> Closed #20 - Add Monad type class instance for Future

README.md
=> Added: Bintray badge

src/main/scala/kevinlee/fp/Functor.scala, src/main/scala/kevinlee/fp/Monad.scala, src/test/scala/kevinlee/fp/FunctorSpec.scala, src/test/scala/kevinlee/fp/Specs.scala
Closed #33 - Add Functor type class instance for Future
=> Closed #33 - Add Functor type class instance for Future

changelogs/0.4.0.md, project/ProjectInfo.scala
[0.4.0](https://github.com/Kevin-Lee/just-fp/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+milestone%3A%22milestone4%22)
* Add Functor type class instance for Future (#33)
=> just-fp v0.4.0

project/Deps.scala
=> Changed: upgraded Hedgehog

src/main/scala-2.10/kevinlee/fp/compat/EitherCompat.scala, src/main/scala-2.11/kevinlee/fp/compat/EitherCompat.scala, src/main/scala-2.12/kevinlee/fp/compat/EitherCompat.scala, src/main/scala/kevinlee/fp/EitherT.scala
Close #37 - Stop using RightProjection
=> Close #37 - Stop using RightProjection

src/main/scala/kevinlee/fp/EitherT.scala, src/main/scala/kevinlee/fp/Fp.scala, src/main/scala/kevinlee/fp/Implicits.scala, src/main/scala/kevinlee/fp/JustSyntax.scala, src/main/scala/kevinlee/fp/syntax/eithers.scala, src/test/scala/kevinlee/fp/syntax/EitherOpsSpec.scala
Close #41 - Change Implicits to JustSyntax
=> Close #41 - Change Implicits to JustSyntax

build.sbt, project/ProjectInfo.scala, project/plugins.sbt, src/main/scala-2.13/kevinlee/fp/compat/EitherCompat.scala
=> Support scala 2.13

build.sbt, project/ProjectInfo.scala, project/plugins.sbt
Close #39 - Support Scala 2.13
=> Close #39 - Support Scala 2.13

changelogs/1.0.0.md, project/ProjectInfo.scala
=> Prepare to release 1.0.0

src/main/scala/just/fp/Equal.scala, src/main/scala/just/fp/Monoid.scala, src/main/scala/just/fp/instances/ByteInstances.scala, src/test/scala/just/fp/Gens.scala, src/test/scala/just/fp/MonoidSpec.scala, src/test/scala/just/fp/Specs.scala
Close #54 - Add Monoid for Int based types, BigInt, BigDecimal and String
=> Close #54 - Add Monoid for Int based types, BigInt, BigDecimal and String

src/main/scala/just/fp/JustSyntax.scala, src/main/scala/just/fp/Monoid.scala, src/main/scala/just/fp/SemiGroup.scala, src/main/scala/just/fp/syntax/SemiGroupSyntax.scala, src/test/scala/just/fp/syntax/SemiGroupSyntaxSpec.scala
Close #56 - Add SemiGroup syntax
=> Close #56 - Add SemiGroup syntax

src/main/scala-2.10_2.11/just/fp/compat/EitherCompat.scala, src/main/scala-2.12_2.13/just/fp/compat/EitherCompat.scala, src/main/scala/just/fp/Applicative.scala, src/main/scala/just/fp/EitherT.scala, src/main/scala/just/fp/Equal.scala, src/main/scala/just/fp/Functor.scala, src/main/scala/just/fp/Monad.scala, src/main/scala/just/fp/WriterT.scala, src/test/scala/just/fp/FunctorSpec.scala, src/test/scala/just/fp/Gens.scala
Close #61 - Rewrite Functor, Applicative and Monad instances
=> Close #61 - Rewrite Functor, Applicative and Monad instances

src/main/scala/just/fp/Applicative.scala, src/main/scala/just/fp/Equal.scala, src/main/scala/just/fp/Functor.scala, src/main/scala/just/fp/Monad.scala, src/test/scala/just/fp/ApplicativeSpec.scala, src/test/scala/just/fp/FunctorSpec.scala, src/test/scala/just/fp/Specs.scala
=> Close #60 - Add OptionMonad

src/main/scala/just/fp/WriterT.scala, src/test/scala/just/fp/ApplicativeSpec.scala, src/test/scala/just/fp/FunctorSpec.scala, src/test/scala/just/fp/Gens.scala, src/test/scala/just/fp/MonadSpec.scala, src/test/scala/just/fp/Specs.scala, src/test/scala/just/fp/WriterTSpec.scala, src/test/scala/just/fp/testing/EqualUtil.scala
Close #58 - Add more `WriterT` instances
=> Close #58 - Add more WriterT instances

src/main/scala/just/fp/EitherT.scala, src/test/scala/just/fp/EitherTSpec.scala, src/test/scala/just/fp/Gens.scala
Close #59 - Add more `EitherT` instances
=> Close #59 - Add more EitherT instances

README.md, changelogs/1.1.0.md, project/ProjectInfo.scala
=> Prepare to release 1.1.0

src/main/scala/just/fp/Applicative.scala, src/main/scala/just/fp/EitherT.scala, src/main/scala/just/fp/Functor.scala, src/main/scala/just/fp/Monad.scala, src/main/scala/just/fp/WriterT.scala, src/test/scala/just/fp/ApplicativeSpec.scala, src/test/scala/just/fp/FunctorSpec.scala, src/test/scala/just/fp/MonadSpec.scala
Close #68 - Replace `?` with `*`
=> Close #68 - Replace ? with *

src/main/scala/just/fp/EitherT.scala, src/main/scala/just/fp/JustSyntax.scala, src/main/scala/just/fp/syntax/package.scala, src/test/scala/just/fp/syntax/EitherOpsSpec.scala, src/test/scala/just/fp/syntax/EqualSyntaxSpec.scala, src/test/scala/just/fp/syntax/SemiGroupSyntaxSpec.scala, src/test/scala/just/fp/testing/EqualUtil.scala
Close #71 - Change JustSyntax to syntax
=> Close #71 - Change JustSyntax to syntax

src/main/scala/just/fp/syntax/OptionSyntax.scala, src/main/scala/just/fp/syntax/package.scala, src/test/scala/just/fp/syntax/OptionSyntaxSpec.scala, src/test/scala/just/fp/testing/TypeUtil.scala
=> Close #72 - Add OptionSyntax

src/main/scala/just/fp/syntax/OptionSyntax.scala, src/test/scala/just/fp/syntax/OptionSyntaxSpec.scala
Close #75 - Add `toEither` to `OptionSyntax`
=> Close #75 - Add toEither to OptionSyntax

README.md, changelogs/1.1.0.md, changelogs/1.2.0.md
=> Prepare to release 1.2.0

build.sbt
=> Minor change in build.sbt

build.sbt, project/ProjectInfo.scala, project/plugins.sbt
Fixed: Scala binary incompatibility issue
=> Fixed: Scala binary incompatibility issue

src/main/scala/just/fp/syntax/WriterSyntax.scala, src/main/scala/just/fp/syntax/package.scala, src/test/scala/just/fp/syntax/WriterSyntaxSpec.scala
Close #89 - Add `writer` syntax
=> Close #89 - Add writer syntax

.build-scripts/build-project-simple.sh, .build-scripts/build-project.sh
Changes in build script to check branch for proper packaging
=> Changes in build script to check branch for proper packaging

README.md
Changed: README.md updated with some initial documentation for Either
=> Changed: README.md updated with some initial documentation for Either

README.md
Upgraded: `README.md` - `Option` Constructors and Type-safe `Equal`
=> Upgraded: README.md - Option Constructors and Type-safe Equal

README.md
Updated: README.md - document for `SemiGroup`
=> Updated: README.md - document for SemiGroup

src/test/scala/just/fp/MonoidSpec.scala
Clean up test (related to Task #104)
=> Clean up test (related to Task #104)

src/main/scala/just/fp/Monoid.scala, src/test/scala/just/fp/MonoidSpec.scala
Close #106 - Add `nonZero` to `Monoid`
=> Close #106 - Add nonZero to Monoid

README.md, changelogs/1.3.1.md, project/ProjectInfo.scala
=> Prepare to release 1.3.1

project/build.properties
Upgraded: sbt `1.3.1` => `1.3.3`
=> Upgraded: sbt 1.3.1 => 1.3.3

README.md
Updated: `README.md` - Added: `Monoid`
=> Updated: README.md - Added: Monoid

.github/workflows/build.yml, .github/workflows/release.yml, .github/workflows/sbt-build-simple.sh, .github/workflows/sbt-build.sh, README.md, project/plugins.sbt
Close #113 - Set up GitHub Actions
* Added: config and build script files for GitHub Actions
* Added: GitHub Actions build status badges
* Changed: sbt-devoops `0.3.1` => `1.0.0`
=> Close #113 - Set up GitHub Actions

README.md, project/Deps.scala
* Changed: build status badges with the specific build links
* Upgraded: Hedgehog
=> Update README and upgrade lib

build.sbt
Changed: Group ID from `kevinlee` to `io.kevinlee` for publishing to some central repo.
=> Changed: Group ID from kevinlee to io.kevinlee for publishing to some central repo

project/Deps.scala
Changed: Hedgehog repo: ivy style => maven style
=> Changed: Hedgehog repo: ivy style => maven style

README.md, build.sbt, changelogs/1.3.3.md, project/ProjectInfo.scala
* Nothing. It is released just to sign the artifacts with GPG.
=> just-fp v1.3.3

README.md, build.sbt, changelogs/1.3.4.md, project/ProjectInfo.scala
* Only project homepage and scm info have been added for release.
=> just-fp v1.3.4

README.md
Updated: README.md
* added: maven central badge
=> Updated: README.md - added: maven central badge

build.sbt
Added: Ammonite-REPL for a quick try in console (`test:run`)
=> Added: Ammonite-REPL for a quick try in console (test:run)

README.md, project/plugins.sbt
* Updated: `README.md` - Scaladex badges
* Upgraded: `sbt-devoops` `1.0.0` => `1.0.2`
=> Updated: README.md / Upgraded: sbt-devoops

.github/workflows/release.yml, .github/workflows/sbt-build-simple.sh, .github/workflows/sbt-build.sh
* Fixed: The build script doesn't fail when build fails.
* Removed: unnecessary env var (It was also incorrect.)
=> Fixed: build scripts

README.md, changelogs/1.3.5.md, project/ProjectInfo.scala
* Use GitHub Actions for Maven Central sync (#127)
(Internal CI / CD change)
=> Prepare to release v1.3.5

.github/workflows/release.yml
Separate GitHub Actions job step for Maven Central sync
=> Separate GitHub Actions job step for Maven Central sync

project/build.properties
=> Upgraded: sbt 1.3.3 => 1.3.4

src/main/scala/just/fp/OptionT.scala, src/test/scala/just/fp/Gens.scala, src/test/scala/just/fp/OptionTSpec.scala
=> Close #132 - Add OptionT

build.sbt, project/ProjectInfo.scala, project/plugins.sbt
Upgraded - sbt-devoops 1.0.2 => 1.0.3
=> Upgraded - sbt-devoops 1.0.2 => 1.0.3

project/build.properties
=> Upgraded - sbt 1.3.4 => 1.3.5

project/build.properties
=> Upgraded - sbt 1.3.5 => 1.3.6

.github/workflows/build.yml
Changed: GitHub Actions - Cross Scala version build using matrix
=> Changed: GitHub Actions - Cross Scala version build using matrix

project/build.properties
=> Upgraded - sbt 1.3.6 => 1.3.7

docs/docs/docs/typeclass/functor.md
=> Updated: docs - Functor

build.sbt, project/plugins.sbt
Upgraded - wartremover and ammonite
* wartremover: 2.4.3 => 2.4.5
* ammonite: 1.7.4 => 2.0.4
=> Upgraded - wartremover and ammonite

project/plugins.sbt
=> Upgraded - sbt-microsites 1.0.2 => 1.1.4

build.sbt
=> Upgraded: Hedgehog

build.sbt
Changed: WartRemover is enabled in IDEA but not in console
=> Changed: WartRemover is enabled in IDEA but not in console

.build-scripts/build-project-simple.sh, .build-scripts/build-project.sh, .github/workflows/sbt-build-simple.sh, .github/workflows/sbt-build.sh, PULL_REQUEST_TEMPLATE.md, README.md, docs/docs/index.md
Changed: all CI config for the master branch to the main branch
=> Changed: all CI config for the master branch to the main branch

.github/workflows/publish-github-pages.yml, README.md, build.sbt, project/plugins.sbt, website/static/CNAME
Close #165 - Replace `sbt-microsites` with `Docusaurus`
=> Close #165 - Replace sbt-microsites with Docusaurus

website/src/pages/index.js
Changed: site head info (i.e. title and description)
=> Changed: site head info (i.e. title and description)

.github/workflows/build.yml
Set a proper `CI_BRANCH` for push build
=> Set a proper CI_BRANCH for push build

.github/workflows/build.yml
=> Added: Build numbers in CI

.github/workflows/build.yml
=> Fix: Build info in CI

docs/getting-started.md
Changed: The build all status badge in doc
=> Changed: The build all status badge in doc

.github/workflows/build.yml
Added: Scala name - Scala | Dotty
=> Added: Scala name - Scala | Dotty

project/build.properties
Upgraded: sbt `1.3.13` => `1.4.2`
=> Upgraded: sbt 1.3.13 => 1.4.2

.github/workflows/maven_central_sync.sh, .github/workflows/release.yml, .github/workflows/sbt-build-all.sh, .github/workflows/sbt-build.sh, project/build.properties
Upgraded: sbt `1.3.13` => `1.4.3`
* The environment variable `SOURCE_DATE_EPOCH` is set.
* Added: A script file for maven central sync
=> Upgraded: sbt 1.3.13 => 1.4.3

.github/workflows/build.yml, .github/workflows/release.yml, build.sbt
Close #180 - Support Scala `3.0.0-M2`
=> Close #180 - Support Scala 3.0.0-M2

.github/workflows/release.yml, .github/workflows/sbt-build-all.sh, .github/workflows/sbt-build.sh
Fixed: The wrong timestamps in the artifacts
=> Fixed: The wrong timestamps in the artifacts

project/build.properties
Upgraded: sbt `1.4.3` => `1.4.9`
=> Upgraded: sbt 1.4.3 => 1.4.9

build.sbt, project/build.properties
Upgraded: sbt `1.4.9` => `1.5.0`
=> Upgraded: sbt 1.4.9 => 1.5.0

.github/workflows/build.yml
=> Removed: build for PR

.github/workflows/build.yml, .github/workflows/release.yml, build.sbt, project/plugins.sbt
Close #186 - Support Scala `3.0.0-M3`, Scala `3.0.0-RC1` and Scala `3.0.0-RC2`
=> Close #186 - Support Scala 3.0.0-M3, Scala 3.0.0-RC1 and Scala 3.0.0-RC2

.github/workflows/build.yml, .github/workflows/release.yml, .github/workflows/sbt-build-all.sh, build.sbt, project/plugins.sbt
Updated: GitHub Actions config and script for build and release
=> Updated: GitHub Actions config and script for build and release

build.sbt
=> Clean up - build.sbt

.github/workflows/sbt-build-all.sh, .scalafix.conf, build.sbt, core/src/main/scala/just/fp/Equal.scala, core/src/main/scala/just/fp/instances/BigDecimalInstances.scala, core/src/main/scala/just/fp/instances/BigIntInstances.scala, core/src/main/scala/just/fp/instances/BooleanInstances.scala, core/src/main/scala/just/fp/instances/ByteInstances.scala, core/src/main/scala/just/fp/instances/CharInstances.scala, core/src/main/scala/just/fp/instances/DoubleInstances.scala, core/src/main/scala/just/fp/instances/FloatInstances.scala, core/src/main/scala/just/fp/instances/IntInstances.scala, core/src/main/scala/just/fp/instances/LongInstances.scala, core/src/main/scala/just/fp/instances/ShortInstances.scala, core/src/main/scala/just/fp/instances/StringInstances.scala, core/src/main/scala/just/fp/syntax/EitherSyntax.scala, project/plugins.sbt
=> Close #190 - Use Scalafix

.github/workflows/build.yml, .github/workflows/release.yml, build.sbt
Close #192 - Drop Scala `3.0.0-M*` support
=> Close #192 - Drop Scala 3.0.0-M* support

.github/workflows/build.yml, .github/workflows/sbt-build-all.sh
Fixed: broken coveralls report
=> Fixed: broken coveralls report

.github/workflows/release.yml
* Add `OptionT` (#132)
* ~~Add the document site using `sbt-microsites`~~ (#142)
* Add core sub-project (#143)
* Replace `sbt-microsites` with `Docusaurus` (#165)
* Build for Dotty (#170)
* ~~Support Scala `3.0.0-M2`~~ (#180)
* Support ~~Scala `3.0.0-M3`~~, Scala `3.0.0-RC1` and Scala `3.0.0-RC2` (#186)
* Use `Scalafix` (#190)
* Drop Scala `3.0.0-M*` support (#192)
=> just-fp v1.4.0

.github/workflows/publish-github-pages.yml, build.sbt, docs/getting-started.md
=> Updated: docs

.github/workflows/release.yml, .github/workflows/sbt-build-all.sh
Updated: release config and build script for GitHub Actions
=> Updated: release config and build script for GitHub Actions

README.md, docs/getting-started.md
Updated: release status badges
=> Updated: release status badges

.github/workflows/build.yml, build.sbt
Close #202 - Support Scala `3.0.0-RC3`
=> Close #202 - Support Scala 3.0.0-RC3

changelogs/1.5.0.md, project/ProjectInfo.scala
* Support Scala `3.0.0-RC3` (#202)
=> just-fp v1.5.0

build.sbt
Updated: Remove version from `build.sbt`
=> Updated: Remove version from build.sbt

build.sbt
=> Clean up config

build.sbt
Close #210 - Drop Scala `2.10` support
=> Close #210 - Drop Scala 2.10 support

build.sbt, project/build.properties
Updated: Docs and sbt `1.5.0` => `1.5.2`
=> Updated: Docs and sbt 1.5.0 => 1.5.2

core/src/main/scala/just/fp/syntax/EitherSyntax.scala, core/src/main/scala/just/fp/syntax/EqualSyntax.scala, core/src/main/scala/just/fp/syntax/OptionSyntax.scala, core/src/main/scala/just/fp/syntax/SemiGroupSyntax.scala, core/src/main/scala/just/fp/syntax/WriterSyntax.scala, project/plugins.sbt
Upgraded: sbt-devoops `2.3.0` => `2.6.0`
=> Upgraded: sbt-devoops 2.3.0 => 2.6.0

project/build.properties
=> Upgrade sbt 1.5.4 => 1.7.1

build.sbt
=> Fix #223 - Fix release

project/plugins.sbt
Bump sbt-devoops `2.22.0` => `2.23.0` / sbt-docusaur `0.11.0` => `0.12.0`
=> Bump sbt-devoops `2.22.0` => `2.23.0` / sbt-docusaur `0.11.0` => `0.12.0`

build.sbt
Update: build.sbt - add SonatypeSnapshots resolver
=> Update: build.sbt - add SonatypeSnapshots resolver

core/src/main/scala/just/fp/syntax/EqualSyntax.scala, core/src/test/scala/just/fp/MonoidSpec.scala
=> Clean up: Remove unused code

core/src/main/scala/just/fp/syntax/EqualSyntax.scala
Clean up: Remove unnecessary code
=> Clean up: Remove unnecessary code

build.sbt
Update `build.sbt`: Remove unnecessary config property
=> Update `build.sbt`: Remove unnecessary config property

.github/workflows/m-doc-site-publish.yml
Fix GitHub Actions for docs build
=> Fix GitHub Actions for docs build

.github/workflows/build.yml, build.sbt, project/build.properties, project/plugins.sbt
=> Bump sbt to 1.10.0
